source/includes/_webhooks.md.erb
=> Candidate questions in webhook

source/includes/_webhooks.md.erb
Co-Authored-By: piotr-galas <galaspiotrek@gmail.com>
=> add custom-fields to the webhook

source/includes/_webhooks.md.erb
1. fix partner event custom fields - they should not include questions
2. add info about rejection in job object
=> update partner event

source/includes/job_boards/_changelog.md.erb, source/includes/job_boards/_webhooks.md.erb
Connected with https://github.com/Teamtailor/teamtailor/pull/17242
=> Add created-at and duration fields to channels

source/includes/job_boards/direct_apply/_index.md.erb
One of our partners tried to send resume in wrong format. Be more transparent with it in documentation.
=> Let know about base64 resume encoding

source/includes/job_boards/_xml_feeds.md.erb
Connected with https://github.com/Teamtailor/adapters/pull/779
=> Add company uuid to xml feed docs

source/includes/job_boards/direct_apply/_index.md.erb
Connected with https://github.com/Teamtailor/teamtailor/pull/19675
=> Add date and number question types to direct apply

source/includes/partners/_changelog.md.erb, source/includes/partners/_webhooks.md.erb
This PR updates docs due to changes in this PR: https://github.com/Teamtailor/teamtailor/pull/24251
=> Feat: Update webhook docs

source/includes/partners/webhook_config/_index.md.erb
Add object field refetch information
=> Feat: add refetch info

source/includes/partners/webhook_config/_index.md.erb
=> Fix: refetch description

source/includes/partners/_webhooks.md.erb
Move type to related custom field
=> Fix: type outside custom field

source/includes/partners/_webhooks.md.erb
Fix formatting of objects in candidate custom fields
=> Fix: add missing object

source/includes/partners/_changelog.md.erb
Looks like a missed some typos in #54.
=> Fix two typos with `assessment-criteria` in changelog

source/job_boards/direct_apply/index.html.md.erb, source/job_boards/index.html.md.erb
Add index to path to fix cannot find path issue.
=> Fix: webhook activation config path

source/includes/job_boards/_webhook_signatures.md.erb, source/includes/partners/_changelog.md.erb
Use partner event ID to check signature.
=> Improvemnt: signatures v2 

source/includes/job_boards/direct_apply/_index.md.erb
Added direct apply resume file types
=> added resume file types

source/includes/job_boards/_webhook_signatures.md.erb, source/includes/partners/_webhook_signatures.md.erb
Add info about signatures v2 to partners instead of job boards.
=> Fix: signatures for partners

source/includes/job_boards/webhook_activation_config/_index.md.erb
Add more descriptive name for variable of channel id
=> Improvement: channel id for activation config

source/includes/job_boards/webhook_activation_config/_index.md.erb, source/includes/partners/webhook_activation_config/_index.md.erb
Fix routes to match actual param
=> fix routes

source/includes/partners/_changelog.md.erb, source/includes/partners/_webhooks.md.erb
Add referrals data to webhook.
[Notion card](https://www.notion.so/teamtailor/Referrer-field-webhook-82a54a4f6ce24660aff11265646f875c?pvs=4)
=> Improvement: add referrals webhook info

source/includes/partners/partner_results/_create.md.erb
Candidate id was a missing param in partner result create.
=> Improvement: Partner result candidate

source/includes/home/_intro.md.erb
Missed one by misstake - https://github.com/Teamtailor/tt-partner-docs/pull/79
=> Another updated emailaddress

lib/routes.rb, source/company_webhooks/index.html.md.erb, source/includes/company_webhooks/_authentication.md.erb, source/includes/company_webhooks/_best_practices.md.erb, source/includes/company_webhooks/_event_types.md.erb, source/includes/company_webhooks/_intro.md.erb, source/includes/company_webhooks/_payloads.md.erb, source/includes/company_webhooks/_setup.md.erb, source/includes/company_webhooks/_signatures.md.erb, source/includes/home/_intro.md.erb
Adding documentation for Webhooks as part of [this project](https://www.notion.so/teamtailor/76579e017c494f6eb7034772ba1b05b7?v=17a885a70ca1803baa44000c75bb054e&p=94a6284fc1854cc59f93ea83cd7c830d&pm=s)
=> Feat: Company webhooks documentation

source/company_webhooks/index.html.md.erb, source/includes/company_webhooks/_intro.md.erb, source/includes/company_webhooks/_webhook_setups.md.erb
added webhook setups info to webhook documentation
=> Feat: webhook setups info

source/includes/partners/_webhooks.md.erb
Close https://github.com/Teamtailor/teamtailor/issues/38921
=> Fix: add info about how to turn on job offers
